Update ci-cd-pipeline.yml

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -16,8 +16,8 @@ env:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
-    steps:
+  runs-on: ubuntu-latest
+  steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
 
@@ -35,10 +35,10 @@ jobs:
         echo "FRONTEND_IMAGE_ID=$(docker images -q ecommerce-frontend:latest)" >> $GITHUB_ENV
 
 
-  push_to_ecr:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
+push_to_ecr:
+ runs-on: ubuntu-latest
+ needs: build
+ steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
 
@@ -56,13 +56,16 @@ jobs:
 
     - name: Tag and Push Frontend Image
       run: |
+        if [[ -z "$FRONTEND_IMAGE_ID" ]]; then echo "Error: FRONTEND_IMAGE_ID is empty"; exit 1; fi
         docker tag $FRONTEND_IMAGE_ID $FRONTEND_ECR:latest
         docker push $FRONTEND_ECR:latest
 
     - name: Tag and Push Backend Image
       run: |
+        if [[ -z "$BACKEND_IMAGE_ID" ]]; then echo "Error: BACKEND_IMAGE_ID is empty"; exit 1; fi
         docker tag $BACKEND_IMAGE_ID $BACKEND_ECR:latest
         docker push $BACKEND_ECR:latest
+
 
 
 
